"""Local Ant FastAPI server.

Endpoints
---------
GET  /api/health                  -> {"ok": true, ...}
POST /api/analyze                 -> SSE stream of progress + final JSON payload
                                     (multipart upload field `video`)

Run with:
    uvicorn server.app:app --host 127.0.0.1 --port 8090 --reload
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import shutil
import sys
import tempfile
import threading
import time
import traceback
import uuid
from pathlib import Path
from typing import AsyncGenerator
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from fastapi import FastAPI, File, HTTPException, Request, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field


from server.local_pipeline import BRAIN_RENDERS_DIR, POPULATION_SIZE, build_payload


logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("ant.local")

app = FastAPI(title="ant-local", version="0.1.0")

# CORS allowlist. Override with ANT_ALLOWED_ORIGINS="https://a,https://b".
# Public release: only the deployed frontend + local dev. Wildcard is a DoS /
# free-GPU-abuse risk because /api/analyze has no auth.
_default_allowed_origins = [
    "https://g9jy59jq.insforge.site",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
_env_allowed = os.environ.get("ANT_ALLOWED_ORIGINS", "").strip()
ALLOWED_ORIGINS = (
    [o.strip() for o in _env_allowed.split(",") if o.strip()]
    if _env_allowed
    else _default_allowed_origins
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type", "Authorization", "X-Ant-Token"],
)

# Serve the interactive nilearn brain renders generated by build_brain_payload.
# Path is also imported by the pipeline so both sides agree on the location.
try:
    BRAIN_RENDERS_DIR.mkdir(parents=True, exist_ok=True)
except Exception as _e:  # noqa: BLE001
    logger.warning("brain renders dir unavailable: %r", _e)
app.mount("/brain", StaticFiles(directory=str(BRAIN_RENDERS_DIR)), name="brain")


UPLOAD_DIR = Path(tempfile.gettempdir()) / "ant_uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://127.0.0.1:11434")
OLLAMA_CHAT_MODEL = os.environ.get("OLLAMA_CHAT_MODEL", "qwen2.5:0.5b")
# Max upload size for /api/analyze. Override via ANT_MAX_UPLOAD_BYTES.
MAX_UPLOAD_BYTES = int(os.environ.get("ANT_MAX_UPLOAD_BYTES", str(100 * 1024 * 1024)))
# Optional shared secret. If set, /api/analyze requires header X-Ant-Token to match.
# Recommended for public release: set this on the Vast box and in the edge function env.
ANT_SHARED_TOKEN = os.environ.get("ANT_SHARED_TOKEN", "").strip()


class ChatTurn(BaseModel):
    role: str
    text: str


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000)
    history: list[ChatTurn] = Field(default_factory=list)
    agent: dict | None = None


@app.get("/api/health")
def health() -> dict:
    # Public endpoint — return only liveness. We used to return
    # {device, torch_version, population_size}, which fingerprints the host
    # (GPU model attackable via CVEs, torch version → known dep CVEs) for
    # anyone curling the box. Liveness is all the frontend needs.
    return {"ok": True}


def _ollama_chat(payload: ChatRequest) -> str:
    """Call local Ollama for the Olivia persona chat."""
    history = payload.history[-10:]
    system = (
        "You are Olivia Kowalski, a privacy-conscious Berlin barista in her early 30s. "
        "You are married, balancing two young children and an intense work ethic. "
        "You are socially driven, curious about new experiences, values-first, and drawn to authentic local communities. "
        "You liked the local cafe discovery app concept most because it connects to your professional identity and love of meaningful discovery. "
        "Reply in first person as Olivia. Keep answers conversational, grounded, and concise: 1-3 sentences. "
        "Do not mention that you are an AI model or that this is a simulation."
    )
    messages = [{"role": "system", "content": system}]
    for turn in history:
        role = "assistant" if turn.role == "agent" else "user"
        text = str(turn.text or "").strip()
        if text:
            messages.append({"role": role, "content": text[:1200]})
    messages.append({"role": "user", "content": payload.message.strip()[:2000]})

    body = json.dumps({
        "model": OLLAMA_CHAT_MODEL,
        "messages": messages,
        "stream": False,
        "options": {
            "temperature": 0.65,
            "top_p": 0.9,
            "num_predict": 120,
        },
    }).encode("utf-8")
    req = Request(
        f"{OLLAMA_URL.rstrip('/')}/api/chat",
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urlopen(req, timeout=25) as resp:  # noqa: S310 - local development endpoint
        data = json.loads(resp.read().decode("utf-8"))
    answer = str((data.get("message") or {}).get("content") or "").strip()
    return answer or "I need a second to think about that."


@app.post("/api/chat")
async def chat(request: Request, payload: ChatRequest) -> JSONResponse:
    _require_shared_token(request.headers)
    try:
        reply = await asyncio.to_thread(_ollama_chat, payload)
        return JSONResponse({
            "ok": True,
            "reply": reply,
            "model": OLLAMA_CHAT_MODEL,
            "persona": "Olivia Kowalski",
        })
    except (HTTPError, URLError, TimeoutError, OSError, json.JSONDecodeError) as exc:
        logger.warning("Ollama chat unavailable: %r", exc)
        return JSONResponse(
            {
                "ok": False,
                "error": f"Ollama unavailable for {OLLAMA_CHAT_MODEL}",
                "reply": "I'm Olivia. I still care most about whether this feels authentic and useful for real neighborhood discovery.",
                "model": OLLAMA_CHAT_MODEL,
                "persona": "Olivia Kowalski",
            },
            status_code=200,
        )


def _sanitize_filename(raw: str) -> str:
    name = (raw or "video.mp4")
    # Strip path separators, NUL bytes, leading dots/dashes; whitelist chars.
    name = name.replace("/", "_").replace("\\", "_").replace("\x00", "")
    name = name.lstrip(". -")
    # Whitelist safe chars; everything else becomes "_".
    cleaned = "".join(c if (c.isalnum() or c in "._-") else "_" for c in name)
    cleaned = cleaned[:120] or "video.mp4"
    return cleaned


class UploadTooLarge(HTTPException):
    def __init__(self, limit: int) -> None:
        super().__init__(413, f"upload exceeds {limit} bytes")


def _save_upload(upload: UploadFile) -> Path:
    safe_name = _sanitize_filename(upload.filename or "video.mp4")
    target = UPLOAD_DIR / f"{uuid.uuid4().hex}_{safe_name}"
    bytes_written = 0
    chunk_size = 1024 * 1024  # 1 MiB
    try:
        with target.open("wb") as out:
            while True:
                chunk = upload.file.read(chunk_size)
                if not chunk:
                    break
                bytes_written += len(chunk)
                if bytes_written > MAX_UPLOAD_BYTES:
                    out.close()
                    target.unlink(missing_ok=True)
                    raise UploadTooLarge(MAX_UPLOAD_BYTES)
                out.write(chunk)
    except UploadTooLarge:
        raise
    except Exception:
        target.unlink(missing_ok=True)
        raise
    return target


def _require_shared_token(request_headers) -> None:
    if not ANT_SHARED_TOKEN:
        return  # disabled
    provided = (request_headers.get("x-ant-token") or "").strip()
    if provided != ANT_SHARED_TOKEN:
        raise HTTPException(401, "missing or invalid X-Ant-Token")


@app.post("/api/analyze")
async def analyze(request: Request, video: UploadFile = File(...)) -> StreamingResponse:
    _require_shared_token(request.headers)
    if not video.filename:
        raise HTTPException(400, "No video filename provided")

    try:
        video_path = _save_upload(video)
    except UploadTooLarge:
        raise
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(500, f"upload save failed: {exc}") from exc

    try:
        size = video_path.stat().st_size
    except Exception:  # noqa: BLE001
        size = 0

    video_meta = {
        "video_name": video.filename,
        "video_size": size,
        "video_type": video.content_type or "video/mp4",
        "video_key": video_path.name,
    }

    queue: asyncio.Queue = asyncio.Queue()
    loop = asyncio.get_event_loop()

    def progress_callback(stage: str, label: str, pct: float) -> None:
        loop.call_soon_threadsafe(queue.put_nowait, {"type": "progress", "stage": stage, "label": label, "pct": pct})

    state = {"payload": None, "error": None}

    def runner() -> None:
        try:
            payload = build_payload(video_path, video_meta, progress_callback=progress_callback)
            state["payload"] = payload
        except Exception as exc:  # noqa: BLE001
            logger.error("Pipeline failed: %s\n%s", exc, traceback.format_exc())
            state["error"] = str(exc)
        finally:
            loop.call_soon_threadsafe(queue.put_nowait, {"type": "__done__"})
            try:
                video_path.unlink(missing_ok=True)
            except Exception:  # noqa: BLE001
                pass

    thread = threading.Thread(target=runner, daemon=True)
    thread.start()

    async def stream() -> AsyncGenerator[bytes, None]:
        yield _sse({
            "type": "progress",
            "stage": "received",
            "label": f"Received {video_meta['video_name']} ({size} bytes)",
            "pct": 1.0,
        })
        while True:
            event = await queue.get()
            if event.get("type") == "__done__":
                break
            yield _sse(event)
        if state["error"]:
            yield _sse({"type": "error", "error": state["error"]})
        elif state["payload"] is not None:
            yield _sse({"type": "result", "payload": state["payload"]})
        else:
            yield _sse({"type": "error", "error": "pipeline returned no payload"})

    return StreamingResponse(stream(), media_type="text/event-stream", headers={
        "Cache-Control": "no-cache",
        "X-Accel-Buffering": "no",
        "Connection": "keep-alive",
    })


def _sse(payload: dict) -> bytes:
    return f"data: {json.dumps(payload, ensure_ascii=False)}\n\n".encode("utf-8")


if __name__ == "__main__":  # pragma: no cover
    import uvicorn
    uvicorn.run("server.app:app", host="127.0.0.1", port=int(os.environ.get("PORT", 8090)))
